// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from exception.djinni

#include <iostream> // for debugging
#include <cassert>
#include "wrapper_marshal.hpp"
#include "cpp_exception.hpp"

#include "cw__cpp_exception.hpp"

std::shared_ptr<::testsuite::CppException> DjinniWrapperCppException::get(djinni::WrapperRef<DjinniWrapperCppException> dw) {
    if (dw) {
        return dw->wrapped_obj;
    }
    return nullptr;
}

void cpp_exception___wrapper_add_ref(DjinniWrapperCppException * dh) {
    dh->ref_count.fetch_add(1);
}
void cpp_exception___wrapper_dec_ref(DjinniWrapperCppException * dh) {
    const size_t ref = dh->ref_count.fetch_sub(1);
    if (ref == 1) {// value before sub is returned
        delete dh;
    }
}
djinni::Handle<DjinniWrapperCppException> DjinniWrapperCppException::wrap(std::shared_ptr<::testsuite::CppException> obj) {
    if (obj)
        return djinni::Handle<DjinniWrapperCppException>(new DjinniWrapperCppException{ std::move(obj) }, cpp_exception___wrapper_dec_ref);
    return nullptr;
}

int32_t cw__cpp_exception_throw_an_exception(DjinniWrapperCppException * djinni_this) {
    try {
        return djinni_this->wrapped_obj->throw_an_exception();
    } CW_TRANSLATE_EXCEPTIONS_RETURN(0);
}
DjinniWrapperCppException * cw__cpp_exception_get(void) {
    try {
        return DjinniWrapperCppException::wrap(::testsuite::CppException::get()).release();
    } CW_TRANSLATE_EXCEPTIONS_RETURN(0);
}
