# AUTOGENERATED FILE - DO NOT MODIFY!
# This file generated by Djinni from foo_duplicate_file_creation.djinni

from djinni.support import MultiSet # default imported in all files
from djinni.exception import CPyException # default imported in all files
from djinni.pycffi_marshal import CPyRecord, CPyString
from PyCFFIlib_cffi import ffi, lib

from djinni import exception # this forces run of __init__.py which gives cpp option to call back into py to create exception

from Foo_Record import FooRecord

class FooRecordHelper:
    @staticmethod
    def release(c_ptr):
        assert c_ptr in c_data_set
        c_data_set.remove(ffi.cast("void*", c_ptr))

    @ffi.callback("struct DjinniString *(struct DjinniRecordHandle *)")
    def get_Foo_Record_f1(cself):
        try:
            with CPyString.fromPy(CPyRecord.toPy(None, cself).a) as py_obj:
                _ret = py_obj.release_djinni_string()
                assert _ret != ffi.NULL
                return _ret
        except Exception as _djinni_py_e:
            CPyException.setExceptionFromPy(_djinni_py_e)
            return ffi.NULL

    @ffi.callback("struct DjinniRecordHandle *(struct DjinniString *)")
    def python_create_Foo_Record(a):
        py_rec = FooRecord(
            CPyString.toPy(a))
        return CPyRecord.fromPy(FooRecord.c_data_set, py_rec) #to do: can be optional?

    @ffi.callback("void (struct DjinniRecordHandle *)")
    def __delete(dh):
        assert dh in FooRecord.c_data_set
        FooRecord.c_data_set.remove(dh)

    @staticmethod
    def _add_callbacks():
        lib.Foo_Record_add_callback___delete(FooRecordHelper.__delete)
        lib.Foo_Record_add_callback_python_create_Foo_Record(FooRecordHelper.python_create_Foo_Record)
        lib.Foo_Record_add_callback_get_Foo_Record_f1(FooRecordHelper.get_Foo_Record_f1)

FooRecordHelper._add_callbacks()

